### ISSUE TITLE
import download_noaa.py depends upon bs4 package

### ISSUE THREAD

**Issue by dwr-psandhu** [CADWRDeltaModeling/vtools3#1]
This is unexpected and needs to be either cleaned up or included in conda package dependencies.

Steps to reproduce.
```
(vtools3-test) D:\dev\test_download>python
Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import vtools.datastore.download_noaa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\Programs\Anaconda2\envs\vtools3-test\lib\site-packages\vtools\datastore\__init__.py", line 2, in <module>
    from .download_noaa import noaa_download
  File "d:\Programs\Anaconda2\envs\vtools3-test\lib\site-packages\vtools\datastore\download_noaa.py", line 8, in <module>
    import bs4
ModuleNotFoundError: No module named 'bs4'
```

**Comment by dwr-psandhu** [comment]
fixed by adding beautifulsoup4 to dependencies. Uploaded to anaconda.org packages
